    var dom = document.getElementById('container');
    var myChart = echarts.init(dom, null, {
        renderer: 'svg',
        useDirtyRect: false
    });
    var app = {};

    var option;

    function getVirtulData(year) {
        const y = year;
        var a = [];
        //window.alert(year);
        
        if (y == 2020) 
        {

            a = [
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-25'))), -1],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-26'))), 9.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-27'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-28'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-29'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-30'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-01-31'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-01'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-02'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-03'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-04'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-05'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-06'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-07'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-08'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-09'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-10'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-11'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-12'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-13'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-14'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-15'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-16'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-17'))), 5.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-18'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-19'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-20'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-21'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-22'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-23'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-24'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-25'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-26'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-27'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-28'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-02-29'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-01'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-02'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-03'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-04'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-05'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-06'))), 2.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-07'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-08'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-09'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-10'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-11'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-12'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-13'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-14'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-15'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-16'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-17'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-18'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-19'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-20'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-21'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-22'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-23'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-24'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-25'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-26'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-27'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-28'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-29'))), 10.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-30'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-03-31'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-01'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-02'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-03'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-04'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-05'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-06'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-07'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-08'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-09'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-15'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-16'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-18'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-20'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-04-21'))), 2.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-05-15'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-01'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-10'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-11'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-12'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-13'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-14'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-15'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-16'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-17'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-18'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-19'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-20'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-21'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-22'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-23'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-24'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-25'))), 5.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-26'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-27'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-28'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-29'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-06-30'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-01'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-02'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-03'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-04'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-05'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-06'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-07'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-08'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-09'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-10'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-11'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-12'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-13'))), 10.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-14'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-15'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-16'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-17'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-18'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-19'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-20'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-21'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-22'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-23'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-24'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-25'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-26'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-27'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-28'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-29'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-30'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-07-31'))), 6],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-01'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-02'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-03'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-04'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-05'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-06'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-07'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-08'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-09'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-10'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-11'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-12'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-13'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-14'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-15'))), 9.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-16'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-17'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-18'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-19'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-20'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-21'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-22'))), 5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-23'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-24'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-25'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-26'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-27'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-28'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-29'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-30'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-08-31'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-01'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-02'))), 10.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-03'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-04'))), 8.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-05'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-06'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-07'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-08'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-09'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-10'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-11'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-12'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-13'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-14'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-15'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-16'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-17'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-18'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-19'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-20'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-21'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-22'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-23'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-24'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-25'))), 10],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-26'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-27'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-28'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-29'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-09-30'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-01'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-02'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-03'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-04'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-05'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-06'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-07'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-08'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-09'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-10'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-11'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-12'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-13'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-14'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-15'))), 6.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-16'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-17'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-18'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-19'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-20'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-21'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-22'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-23'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-24'))), 9],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-25'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-26'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-27'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-28'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-29'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-30'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-10-31'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-01'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-02'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-03'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-04'))), 5.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-05'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-06'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-07'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-08'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-09'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-10'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-11'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-12'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-13'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-14'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-15'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-16'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-17'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-18'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-19'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-20'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-21'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-22'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-23'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-24'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-25'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-26'))), 11.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-27'))), 9.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-28'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-29'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-11-30'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-01'))), 6.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-02'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-03'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-04'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-05'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-06'))), 6.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-07'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-08'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-09'))), 7],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-10'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-11'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-12'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-13'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-14'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-15'))), 8.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-16'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-17'))), 8.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-18'))), 8],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-19'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-20'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-21'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-22'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-23'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-24'))), 7.25],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-25'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-26'))), 7.75],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-27'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-28'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-29'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-30'))), 7.5],
                [echarts.format.formatTime('yyyy-MM-dd', (echarts.number.parseDate('2020-12-31'))), 6.75],


            ];

           
            alert("Fin if 1");

        }

        if (y == 2020)
        {
            alert(a);
            const data = a
            return data;
        }

        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    

    }



    // 2021



    option = {
        tooltip: {
            position: 'top',
            formatter: function(p) {
                var format = echarts.format.formatTime('yyyy-MM-dd', p.data[0]);
                return format + ': ' + p.data[1];
            }
        },
        visualMap: {
            min: 1.25,
            max: 11.25,
            calculable: true,
            orient: 'vertical',
            left: '650',
            top: 'center'
        },
        calendar: [{
            orient: 'vertical',
            range: '2020'
        }, {
            left: 300,
            orient: 'vertical',
            range: '2021'
        }, {
            left: 520,
            cellSize: [20, 'auto'],
            bottom: 10,
            orient: 'vertical',
            range: '2022',
            dayLabel: {
                margin: 5
            }
        }],
        series: [{
            type: 'heatmap',
            coordinateSystem: 'calendar',
            calendarIndex: 0,
            data: getVirtulData('2020')
        }, {
            type: 'heatmap',
            coordinateSystem: 'calendar',
            calendarIndex: 1,
            data: getVirtulData('2021')
        }, {
            type: 'heatmap',
            coordinateSystem: 'calendar',
            calendarIndex: 2,
            data: getVirtulData('2022')
        }]
    };

    if (option && typeof option === 'object') {
        myChart.setOption(option);
    }

    window.addEventListener('resize', myChart.resize);